# -*- coding: utf-8 -*-
"""genai-tour-planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/debajyotid/e9415f6d9d1059eaaeb7671f8bb88ef8/genai-tour-planner.ipynb
"""

pip install openai langchain-openai streamlit requests googlemaps

import streamlit as st
import openai
import googlemaps

openai.api_key = "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"
OPENAI_API_KEY="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"

st.title("AI Trip Planner")
destination = st.text_input("Enter your destination:")
start_date = st.date_input("Start Date")
end_date = st.date_input("End Date")
budget = st.number_input("Enter your budget (£):", min_value=0)
interests = st.multiselect("Select your interests:",
                          ["Nature", "History", "Food", "Adventure", "Shopping", "Relaxation"]
                           )

def generate_itinerary(destination, start_date, end_date, interests):
    prompt = f"""
    I am planning a trip to {destination} from {start_date} to {end_date}.
    My interests are {', '.join(interests)}.
    Please create a day-by-day itinerary including activities, restaurants, and must-see attractions.
    """
    response = openai.Completion.create(engine="text-davinci-003",prompt=prompt,max_tokens=500)
    return response['choices'][0]['text']

if destination:
    itinerary = generate_itinerary(destination, start_date, end_date, interests)
    st.text_area("Your AI-generated itinerary:", itinerary)

gmaps = googlemaps.Client(key="AIzaSyAoLmUXOSLCPn9qOELr3h75Ytdi4Yadrro")

def get_attractions(destination):
    places_result = gmaps.places_nearby(location=destination,radius=5000,type='tourist_attraction')
    return [place['name'] for place in places_result['results']]

if destination:
    attractions = get_attractions(destination)
    st.write("Top Attractions:", attractions)

import requests

def get_weather(destination):
    api_key = "e6ebe6a7ef129090ec832157bcfc94e1"
    url = f"http://api.openweathermap.org/data/2.5/weather?q={destination}&appid={api_key}"
    response = requests.get(url).json()
    return response['weather'][0]['description']

if destination:
    weather = get_weather(destination)
    st.write(f"Weather in {destination}: {weather}")

from langchain.chains import ConversationChain
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(temperature=0, api_key=OPENAI_API_KEY)

conversation = ConversationChain(llm=llm)

user_message = st.text_input("Refine your plan by asking questions:")
if user_message:
    reply = conversation.run(input=user_message)
    st.write(reply)

if st.button("Generate Plan"):
    # Call the AI model and APIs here
    st.write("Generating your trip plan...")
    generate_itinerary(destination, start_date, end_date, interests)
    get_attractions(destination)
    get_weather(destination)

st.header("Your Final Itinerary")
st.write(itinerary)
st.write("Top Attractions:", ", ".join(attractions))
st.write(f"Weather Forecast: {weather}")